site_name: Embedded Blogs
theme: 
   name: material
   features:
      -  search.suggest
      -  search.highlight
      -  content.tabs.link
   plugins:
     - search
   palette: 
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
nav:
- Embedded: "index.md"
- Youtube:
  - Altium Designer: "youtube/altium-designer.md"
  - The Engineering Mindset: "youtube/engineering-mindset.md"
- Embedded Expert: 
  - Phil-Koopman: "embedded/phil.md"
  - Shawn Hymel Digikey: "embedded/shawn-hymel-digikey.md"
- Embedded Linux: 
  - The Linux Foundation: "embedded-linux/the-linux-foundation.md"
  - Cool Camera: "embedded-linux/cool-camera.md"
  - Tech A Byte: "embedded-linux/tech-byte.md"