site_name: Embedded Blogs
theme: 
   name: material
   features:
      -  search.suggest
      -  search.highlight
      -  content.tabs.link
   plugins:
     - search
   palette: 
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

nav:
- Embedded Roadmap  : "index.md"
- Embedded Expert   : 
  - Phil Koopman    : "embedded/phil.md"
  - Shawn Hymel Digikey: "embedded/shawn-hymel-digikey.md"
  - Embedded for all : "embedded/embedded-for-all.md"
  - Learn embedded systems : "embedded/learn-embedded-systems.md"
  - Neso acedemy    : "embedded/neso-acedemy.md"
  - Shriram vasudevan : "embedded/shriram-vasudevan.md"
- Embedded Technology :
  - Linux Kernel							: "embedded-tech/Readme.md"
  - Bootloaders							  : "embedded-tech/Readme.md"
  - File Systems							: "embedded-tech/Readme.md"
  - Build Systems						  : "embedded-tech/Readme.md"	
  - Package Managers					: "embedded-tech/Readme.md"	
  - Real Time Linux						: "embedded-tech/Readme.md"	
  - Device Drivers						: "embedded-tech/Readme.md"	
  - Frameworks and Libraries	: "embedded-tech/Readme.md"			
  - Security Features					: "embedded-tech/Readme.md"		
  - Virtualization						: "embedded-tech/Readme.md"	
  - Containerization					: "embedded-tech/Readme.md"	
  - Board Support Packages		: "embedded-tech/Readme.md"			
  - Single Board Computers		: "embedded-tech/Readme.md"			
  - Cross Compilation Toolchains			: "embedded-tech/Readme.md"				
  - Power Management					: "embedded-tech/Readme.md"	
  - Graphics and Display			: "embedded-tech/Readme.md"		
  - Audio and Multimedia			: "embedded-tech/Readme.md"		
  - Networking Protocols			: "embedded-tech/Readme.md"		
  - Debugging and Profiling		: "embedded-tech/Readme.md"			
  - RTOS Integration					: "embedded-tech/Readme.md"	
  - Firmware Updates and OTA Updates		: "embedded-tech/Readme.md"					
  - Embedded Linux Distributions			: "embedded-tech/Readme.md"				
  - Industrial Standards and Protocols	: "embedded-tech/Readme.md"						
  - Cloud Integration					: "embedded-tech/Readme.md"		
  - Documentation and Community Resources: "embedded-tech/Readme.md"							
  - IoT Frameworks						: "embedded-tech/Readme.md"	
  - Machine Learning and AI Integration	: "embedded-tech/Readme.md"						
  - Sensor Integration				: "embedded-tech/Readme.md"		
  - Human Machine Interface HMI			: "embedded-tech/Readme.md"				
  - Localization and Internationalization: "embedded-tech/Readme.md"							
  - Remote Monitoring and Management		: "embedded-tech/Readme.md"					
  - Battery Management				: "embedded-tech/Readme.md"		
  - Safety Critical Systems		: "embedded-tech/Readme.md"			
  - Open Source Hardware Projects		: "embedded-tech/Readme.md"					
- Embedded Linux  : 
  - The Linux Foundation : "embedded-linux/the-linux-foundation.md"
  - Cool Camera     : "embedded-linux/cool-camera.md"
  - Tech A Byte     : "embedded-linux/tech-byte.md"
  - Bootlin         : "embedded-linux/bootlin.md"
  - HariHaran       : "embedded-linux/hariharan.md"
  - Learn Linux TV  : "embedded-linux/learn-linux-tv.md"
  - PhyTec          : "embedded-linux/phytec.md"
  - Techno Genius   : "embedded-linux/techno-genius.md"
  - Open NXP        : "semi-companies/open-nxp.md"
- Youtube :
  - Altium Designer : "youtube/altium-designer.md"
  - The Engineering Mindset : "youtube/engineering-mindset.md"
  - Crash Course    : "youtube/crash-course.md"
  - Engineers Post  : "youtube/engineerspost.md"
  - Lesics          : "youtube/lesics.md"
  - Realpars        : "youtube/realpars.md"
- Skills Youtube:
  - Book Summary    : "skills-youtube/books.md"
  - Practical Life  : "skills-youtube/practical-life.md"