site_name: Embedded Blogs
theme: 
   name: material
   features:
      -  search.suggest
      -  search.highlight
      -  content.tabs.link
   plugins:
     - search
   palette: 
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
nav:
- Embedded: "index.md"
- Embedded Expert: 
  - Phil-Koopman: "embedded/phil-koopman.md"
- Embedded Linux: 
  - Tech A Byte: "embedded-linux/tech-byte.md"